### ISSUE TITLE
Use the SmallRye GraphQL Client instead of a custom-baked client

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/status.quarkus.io#45]

**Comment by jmartisk** [comment]
I've got it ready, but we will need to wait until a Quarkus release that contains SmallRye GraphQL 1.3.0 because we need https://github.com/smallrye/smallrye-graphql/commit/8a879eca6fd02274b1e9bd6a0e0bc4b6f183f308 to be able to inspect error messages from the GH GraphQL api which are not quite spec compliant

**Comment by gsmet** [comment]
That's very cool, @jmartisk .

**Comment by gsmet** [comment]
@jmartisk I merged the upgrade to Quarkus 2.2 so we should be good now?

**Comment by jmartisk** [comment]
@gsmet yeah I'll send a PR as soon as I can, just need to do some cleanups. Thanks!

**Comment by gsmet** [comment]
Cool, looking forward to it as it will be a good example of how I can integrate the GraphQL client into the Quarkus GitHub App framework!
